steps:
  - label: ":jest: Run test suite (run 1/3)"
    key: test-run-1
    command:
      - npm ci
      - npm run test:ci
    env:
      BUILDKITE_ANALYTICS_TOKEN: "${BUILDKITE_ANALYTICS_TOKEN}"
    plugins:
      - docker#v5.10.0:
          image: "node:20-alpine"
          mount-buildkite-agent: false

  - label: ":jest: Run test suite (run 2/3)"
    key: test-run-2
    command:
      - npm ci
      - npm run test:ci
    env:
      BUILDKITE_ANALYTICS_TOKEN: "${BUILDKITE_ANALYTICS_TOKEN}"
    plugins:
      - docker#v5.10.0:
          image: "node:20-alpine"
          mount-buildkite-agent: false

  - label: ":jest: Run test suite (run 3/3)"
    key: test-run-3
    command:
      - npm ci
      - npm run test:ci
    env:
      BUILDKITE_ANALYTICS_TOKEN: "${BUILDKITE_ANALYTICS_TOKEN}"
    plugins:
      - docker#v5.10.0:
          image: "node:20-alpine"
          mount-buildkite-agent: false
